# Generated by Django 4.0.6 on 2022-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Category', max_length=40),
            preserve_default=False,
        ),
    ]
